export default {
  HotPlayData: state => state.HotPlayData,
  HotPlayList: state => state.HotPlayList,
  characteristicRecommendList: state => state.characteristicRecommendList,
  themeTypeList: state => state.themeTypeList,
  roomHardList: state => state.roomHardList,
  searchData: state => state.searchData,
  hotDestinationList: state => state.hotDestinationList,
  hotelDetalis: state => state.hotelDetalis,
  hotelModel: state => state.hotelModel,
  hotelPolicy: state => state.hotelPolicy,
  hotelImage: state => state.hotelImage,
  exteriorList: state => state.exteriorList,
  theLobbyList: state => state.theLobbyList,
  restaurantList: state => state.restaurantList,
  searchHotelRoomFilterObj: state => state.searchHotelRoomFilterObj,
  hotelRoom: state => state.hotelRoom,
  publicAreasList: state => state.publicAreasList,
}
